language: python
python: 
    - '3.8.1'

install: 
    - pip install -r requirements.txt

services:
  - postgresql

before_script:
  - psql -c 'create database studyproject;' -U postgres

script:
    - python manage.py makemigrations
    - python manage.py migrate
    - python manage.py test

deploy:
    provider: heroku
    api_key:
        secure: ec8a84d6-1e62-4c22-9689-d003b980b46f
    app:
        master: studybuddyqt
    skip_cleanup: true